"""Add upload_time and post_metadata columns

Revision ID: 414d3199d969
Revises: efd1401075da
Create Date: 2025-03-07 01:39:39.497458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d3199d969'
down_revision = 'efd1401075da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('post_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_metadata')
        batch_op.drop_column('upload_time')

    # ### end Alembic commands ###
