"""Add image_analysis and blockage_analysis fields to Post model

Revision ID: efd1401075da
Revises: 
Create Date: 2025-03-06 23:29:59.795797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd1401075da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blockage_analysis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('blockage_analysis')
        batch_op.drop_column('image_analysis')

    # ### end Alembic commands ###
